# SPDX-License-Identifier: MIT-0
---
# tasks file for manage-instances
- name: Look for existing Instance IDs File
  ansible.builtin.stat:
    path: "{{ playbook_dir }}/files/inst_ids_{{ env }}.txt"
  register: inst_ids_file

- name: Disable Instances
  ansible.builtin.import_tasks: disable-instances.yml
  when: disable_env is defined and disable_env | bool

- name: Enable Instances
  ansible.builtin.import_tasks: enable-instances.yml
  when: enable_env is defined and enable_env | bool
