---
all:
  hosts:
    localhost:
      ansible_connection: local
      # AAP Variables
      controller_url: "https://aap-aap.apps.cluster-s54l2.dynamic2.redhatworkshops.io" # 2.6
      # OCP Variables
      oc_api_url: "https://api.cluster-s54l2.dynamic2.redhatworkshops.io:6443"
      aap_app_name: "aap-24"
      env_ns: "aap"
      idle_aap: true
      # General Variables
      env: stg
