---
all:
  hosts:
    localhost:
      ansible_connection: local
      # AAP Variables
      controller_url: "https://stg-aap.apps.cluster-url.example.com" # 2.6
      # OCP Variables
      oc_api_url: "https://api.ocp-controller-test.example.com:6443"
      aap_app_name: "aap-24"
      env_ns: "aap"
      idle_aap: true
      # General Variables
      env: stg
