---
# tasks file for aap-version
- name: Query the Controller configuration endpoint
  ansible.builtin.uri:
    url: "{{ controller_url }}/api/"
    method: GET
    status_code: 200
    headers:
      Authorization: "Bearer {{ controller_token }}"
      Content-Type: "application/json"
  register: controller_config

- name: Set aap_version fact
  ansible.builtin.set_fact:
    aap_version: "{{ controller_config.x_api_product_version }}"

- name: Set controller api based on aap_version
  ansible.builtin.set_fact:
    controller_api_url: >-
      {% if aap_version is ansible.builtin.contains("4.5") %}
        "/api/v2/"
      {% elif aap_version is ansible.builtin.contains("2.6") or aap_version is ansible.builtin.contains("2.7") %}
        "/api/controller/v2/"
      {% else %}
        unknown
      {% endif %}

- name: Debug config
  ansible.builtin.debug:
    var: aap_version

- name: Debug controller api_url
  ansible.builtin.debug:
    var: controller_api_url

- name: Debug stuff
  ansible.builtin.debug:
    msg: "I am version 2.4"
  when:
    - aap_version is ansible.builtin.contains("4.5")

- name: Debug stuff
  ansible.builtin.debug:
    msg: "I am version 2.6"
  when:
    - aap_version is ansible.builtin.contains("2.6")
