---
# tasks file for disabling schedules
- name: Look for existing Sched IDs File
  ansible.builtin.stat:
    path: "../sched_ids{{ env }}.txt"
  register: sched_ids_file

- name: Backup and Remove existing Sched IDs File
  when: sched_ids_file.stat.isreg
  block:
    - name: Copy Sched ID file if exists
      ansible.builtin.copy:
        src: "../sched_ids{{ env }}.txt"
        dest: "../sched_ids{{ env }}.txt.bak.%Y%m%d%H%M.%S"
        remote_src: true
        mode: '0644'

    - name: Remove Sched IDs file if exists
      ansible.builtin.file:
        path: "../sched_ids{{ env }}.txt"
        state: absent

- name: Fetch all enabled schedules
  ansible.builtin.uri:
    url: "{{ controller_url }}/{{ controller_api_url | trim }}/schedules/?enabled=true"
    method: GET
    status_code: 200
    headers:
      Authorization: "Bearer {{ controller_token }}"
      Content-Type: "application/json"
  register: enabled_schedules

- name: Create file containing enabled schedule IDs
  ansible.builtin.lineinfile:
    line: "{{ item.id }}"
    path: "../sched_ids{{ env }}.txt"
    create: true
    backup: true
    mode: '0644'
  loop:
    "{{ enabled_schedules.json.results }}"

- name: Disable each schedule found
  ansible.controller.schedule:
    controller_host: "{{ controller_url }}"
    controller_oauthtoken: "{{ controller_token }}"
    name: "{{ item.name }}"
    unified_job_template: "{{ item.summary_fields.unified_job_template.name }}"
    enabled: false
    state: present
  loop: "{{ enabled_schedules.json.results }}"
  when: enabled_schedules.json.count > 0
  loop_control:
    label: "{{ item.name }}"
