---
all:
  hosts:
    localhost:
      ansible_connection: local
      # AAP Variables
      controller_url: "https://aap-controller-url.example.com"
      # OCP Variables
      oc_api_url: "https://api.cluster-ocp-controller-url.example.com:6443"

      # Controller instance name in 2.4
      # AnsibleAutomationPlatform instance name in 2.5
      aap_app_name: "aap"
      env_ns: "aap"
      idle_aap: true
      # General Variables
      env: dev
