---
all:
  hosts:
    localhost:
      ansible_connection: local

      # AAP Variables
      controller_url: "https://aap-aap.apps.cluster-rfhtw-1.dynamic2.redhatworkshops.io"

      # OCP Variables
      oc_api_url: "https://api.cluster-rfhtw-1.dynamic2.redhatworkshops.io:6443"
      aap_app_name: "aap"
      env_ns: "aap"
      idle_aap: true

      # General Variables
      env: dev
