---
all:
  hosts:
    localhost:
      ansible_connection: local
      controller_url: "https://aap-aap.apps.cluster-rfhtw-1.dynamic2.redhatworkshops.io"
      oc_api_url: "https://api.cluster-rfhtw-1.dynamic2.redhatworkshops.io:6443"
      # oc_token: "sha256~wGC4GbpSFpeG2tbaMYyD58-_D0eah2dOyuJFwvqVIfs"
      aap_app_name: "aap"
      env_ns: "aap"
      env: dev
