---
- name: Disable all enabled schedules
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ../group_vars/{{ env | default('all') }}.yml
    - ../vaults/{{ env | default('all') }}.yml
  roles:
    - aap-version
    - disable-schedules
