---
- name: Enable controller schedules and instances post maintenance
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../vaults/{{ env | default('dev') }}.yml
  vars:
    enable_env: true
  tasks:
    - name: Check AAP Access and endpoints
      ansible.builtin.include_role:
        name: aap-access
    - name: Disable Instances
      ansible.builtin.include_role:
        name: manage-instances
    - name: Enable Schedules
      ansible.builtin.include_role:
        name: manage-schedules
