---
- name: Re-enable previously disabled schedules
  hosts: localhost
  gather_facts: false
  vars_files:
    - group_vars/"{{ env | default('all') }}".yml
    - "vaults/{{ env | default('all') }}.yml"
  roles:
    - aap-version
    - enable-schedules
