---
- name: Enable AAP 2.6+ Replicas
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../vaults/{{ env | default('dev') }}.yml
  vars:
    aap_idle: false
  tasks:
    # - name: Check AAP Version
    #   ansible.builtin.include_role:
    #     name: aap-version
    - name: Enable Replicas 2.6+
      ansible.builtin.include_role:
        name: manage-replicas
        tasks_from: enable_2.6.yml
      # when: enable_env is defined and enable_env | bool
