---
- name: Manage controller schedules
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../vaults/{{ env | default('all') }}.yml
  tasks:
    - name: Check AAP Version
      ansible.builtin.include_role:
        name: aap-version
    - name: Enable Schedules
      ansible.builtin.include_role:
        name: manage-schedules
      when: enable_env is defined and enable_env | bool
    - name: Disable Schedules
      ansible.builtin.include_role:
        name: manage-schedules
      when: disable_env is defined and disable_env | bool
