---
- name: Manage AAP Operator for OCP Replicas
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../vaults/{{ env | default('all') }}.yml
  tasks:
    # - name: Check AAP Version
    #   ansible.builtin.include_role:
    #     name: aap-version
    - name: Manage Replicas
      ansible.builtin.include_role:
        name: manage-replicas
