---
- name: Test token validity
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../vaults/{{ env | default('dev') }}.yml
  tasks:
    - name: Check AAP Access and endpoints
      ansible.builtin.include_role:
        name: aap-access
