---
- name: Test vars in group_vars
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - "group_vars/{{ env }}.yml"
    # - "../vaults/{{ env | default('all') }}.yml"
  tasks:
    - name: Print environment
      ansible.builtin.debug:
        var: env

    - name: Print controller_token
      ansible.builtin.debug:
        var: controller_token
