---
- name: Get AAP Operator CSV details
  kubernetes.core.k8s_info:
    api_key: "{{ oc_token }}"
    host: "{{ oc_api_url }}"
    validate_certs: false
    kind: ClusterServiceVersion
    api_version: operators.coreos.com/v1alpha1
    namespace: "{{ env_ns }}"
  register: csv_list

- name: Extract and display AAP Operator version
  vars:
    # Filters the CSV list for names containing 'ansible-automation-platform' and grabs its version
    aap_version: "{{ csv_list.resources | selectattr('metadata.name', 'search', 'aap-operator') | map(attribute='spec.version') | first }}"
  ansible.builtin.debug:
    msg: "The AAP Operator version is: {{ aap_version }}"

- name: Patch gateway to set idle_aap to false
  when: aap_version is version('2.5', '>=')
  kubernetes.core.k8s_json_patch:
    api_key: "{{ oc_token }}"
    host: "{{ oc_api_url }}"
    validate_certs: false  # Set to true if your cluster uses trusted CA certificates
    kind: AnsibleAutomationPlatform
    api_version: aap.ansible.com/v1alpha1 # Update this if your CRD uses a different API version
    namespace: "{{ env_ns }}"
    name: "{{ aap_app_name }}"
    patch:
      - op: add # 'add' acts as a merge/update if the path already exists or creates it if it doesn't
        path: "/spec/idle_aap"
        value: "{{ idle_aap | bool | default(true) }}"
#   aap_version is ansible.builtin.contains("2."
