# SPDX-License-Identifier: MIT-0
---
# tasks file for manage_replicas
- name: Get AAP Operator Version
  ansible.builtin.import_tasks: get-aap-version.yml

- name: Patch gateway idle value
  when: aap_version is version('2.5', '>=')
  ansible.builtin.import_tasks: patch_idle_aap.yml

- name: Scale task and web replicas
  when: aap_version is version('2.4', '>=') and aap_version is version('2.5', '<')
  ansible.builtin.import_tasks: patch_scale_replicas.yml
