---
# Ansible 2.5+
- name: "Patch gateway to set idle_aap value to {{ idle_aap }}"
  kubernetes.core.k8s_json_patch:
    api_key: "{{ oc_token }}"
    host: "{{ oc_api_url }}"
    validate_certs: false  # Set to true if your cluster uses trusted CA certificates
    kind: AnsibleAutomationPlatform
    api_version: aap.ansible.com/v1alpha1 # Update this if your CRD uses a different API version
    namespace: "{{ env_ns }}"
    name: "{{ aap_app_name }}"
    patch:
      - op: add # 'add' acts as a merge/update if the path already exists or creates it if it doesn't
        path: "/spec/idle_aap"
        value: "{{ idle_aap | bool | default(true) }}"
